# Generated by Django 5.1.4 on 2024-12-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=8, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostIDReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='RetrievalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_requests', to='main.citizen')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_requests', to='main.lostidreport')),
            ],
        ),
    ]
